### ISSUE TITLE
nbpy package

### ISSUE THREAD

**Issue by DaanFerdinandusse** [FelixWick/cyclic-boosting-paper#1]
Hey, how do you import from the nbpy package? I can't seem to find how to install this package so that I can use it and try to reproduce the code.

Thanks in advance

**Comment by FelixWick** [comment]
Hi. Yes, nbpy was the proprietary package containing Cyclic Boosting. Unfortunately, it is not open source. I have Cyclic Boosting as a private GitHub repository though and I might open source it soon, so stay tuned ;).

**Comment by DaanFerdinandusse** [comment]
Hey, thank you for your swift response. I'll wait patiently then :)

Daan
